import { DateTime } from 'luxon';
import { Duration } from '../domain/Duration';
import { TimeSlot } from '../domain/TimeSlot';

/** Monday = 1 … Sunday = 7, matching Luxon's `weekday`. */
export type Weekday = 1 | 2 | 3 | 4 | 5 | 6 | 7;

export interface WorkingWindow {
  /** Local wall-clock start, e.g. "09:00". */
  readonly from: string;
  /** Local wall-clock end, e.g. "18:00". */
  readonly to: string;
}

export interface SchedulingPolicyOptions {
  timezone?: string;
  workingDays?: readonly Weekday[];
  windows?: readonly WorkingWindow[];
  slotIntervalMinutes?: number;
  minimumNoticeMinutes?: number;
  bookingHorizonDays?: number;
  bufferMinutes?: number;
  maxPerDay?: number;
  /** Hours a request is held while it waits for approval. */
  approvalWindowHours?: number;
}

/**
 * All the "when can I actually be booked" rules in one place.
 *
 * Kept separate from {@link AvailabilityService} so the rules can be tuned — or
 * swapped for a per-user policy later — without touching the slot-generation
 * algorithm that consumes them.
 */
export class SchedulingPolicy {
  readonly timezone: string;
  readonly workingDays: readonly Weekday[];
  readonly windows: readonly WorkingWindow[];
  readonly slotIntervalMinutes: number;
  readonly minimumNoticeMinutes: number;
  readonly bookingHorizonDays: number;
  readonly bufferMinutes: number;
  readonly maxPerDay: number;
  readonly approvalWindowHours: number;

  constructor(options: SchedulingPolicyOptions = {}) {
    this.timezone = options.timezone ?? 'Asia/Singapore';
    this.workingDays = options.workingDays ?? [1, 2, 3, 4, 5];
    this.windows = options.windows ?? [
      { from: '09:00', to: '12:30' },
      { from: '14:00', to: '18:30' },
    ];
    this.slotIntervalMinutes = options.slotIntervalMinutes ?? 30;
    this.minimumNoticeMinutes = options.minimumNoticeMinutes ?? 120;
    this.bookingHorizonDays = options.bookingHorizonDays ?? 60;
    this.bufferMinutes = options.bufferMinutes ?? 0;
    this.maxPerDay = options.maxPerDay ?? 4;
    this.approvalWindowHours = options.approvalWindowHours ?? 24;
  }

  /** Reads overrides from the environment so hours can change without a redeploy. */
  static fromEnv(env: NodeJS.ProcessEnv = process.env): SchedulingPolicy {
    const int = (value: string | undefined, fallback: number) => {
      const parsed = Number.parseInt(value ?? '', 10);
      return Number.isFinite(parsed) ? parsed : fallback;
    };

    const days = env.BOOKING_WORKING_DAYS?.split(',')
      .map((day) => Number.parseInt(day.trim(), 10))
      .filter((day): day is Weekday => day >= 1 && day <= 7);

    const windows = env.BOOKING_HOURS?.split(',')
      .map((window) => window.trim().split('-'))
      .filter((parts) => parts.length === 2)
      .map(([from, to]) => ({ from: from.trim(), to: to.trim() }));

    return new SchedulingPolicy({
      timezone: env.BOOKING_TIMEZONE || 'Asia/Singapore',
      workingDays: days?.length ? days : undefined,
      windows: windows?.length ? windows : undefined,
      slotIntervalMinutes: int(env.BOOKING_SLOT_INTERVAL, 30),
      minimumNoticeMinutes: int(env.BOOKING_MIN_NOTICE_MINUTES, 120),
      bookingHorizonDays: int(env.BOOKING_HORIZON_DAYS, 60),
      bufferMinutes: int(env.BOOKING_BUFFER_MINUTES, 0),
      maxPerDay: int(env.BOOKING_MAX_PER_DAY, 4),
      approvalWindowHours: int(env.BOOKING_APPROVAL_WINDOW_HOURS, 24),
    });
  }

  isWorkingDay(day: DateTime): boolean {
    return this.workingDays.includes(day.setZone(this.timezone).weekday as Weekday);
  }

  /** When an unanswered request stops holding its slot. */
  holdExpiresFrom(now: DateTime): DateTime {
    return now.plus({ hours: this.approvalWindowHours });
  }

  /** Earliest instant that may be booked, given the notice requirement. */
  earliestBookableFrom(now: DateTime): DateTime {
    return now.plus({ minutes: this.minimumNoticeMinutes });
  }

  /** Last instant that may be booked, given the horizon. */
  latestBookableFrom(now: DateTime): DateTime {
    return now.setZone(this.timezone).plus({ days: this.bookingHorizonDays }).endOf('day');
  }

  isWithinHorizon(slot: TimeSlot, now: DateTime): boolean {
    return slot.start >= this.earliestBookableFrom(now) && slot.start <= this.latestBookableFrom(now);
  }

  /**
   * Every candidate start time for a given local day, as absolute instants.
   *
   * Generated by walking each working window on the `slotIntervalMinutes` grid and
   * keeping only the starts whose full duration still fits inside that window —
   * so a 60-minute session is never offered at 18:00 when the day ends at 18:30.
   */
  candidateSlots(localDay: DateTime, duration: Duration): TimeSlot[] {
    const day = localDay.setZone(this.timezone).startOf('day');
    if (!this.isWorkingDay(day)) return [];

    const slots: TimeSlot[] = [];

    for (const window of this.windows) {
      const windowStart = this.applyWallClock(day, window.from);
      const windowEnd = this.applyWallClock(day, window.to);
      if (!windowStart.isValid || !windowEnd.isValid || windowEnd <= windowStart) continue;

      let cursor = windowStart;
      while (cursor.plus({ minutes: duration.minutes }) <= windowEnd) {
        slots.push(TimeSlot.fromStart(cursor, duration));
        cursor = cursor.plus({ minutes: this.slotIntervalMinutes });
      }
    }

    return slots.sort((a, b) => a.start.toMillis() - b.start.toMillis());
  }

  private applyWallClock(day: DateTime, wallClock: string): DateTime {
    const [hour, minute] = wallClock.split(':').map((part) => Number.parseInt(part, 10));
    return day.set({
      hour: Number.isFinite(hour) ? hour : 0,
      minute: Number.isFinite(minute) ? minute : 0,
      second: 0,
      millisecond: 0,
    });
  }

  /** Serialisable form the browser needs to render hints and the legend. */
  toClientConfig() {
    return {
      timezone: this.timezone,
      workingDays: this.workingDays,
      windows: this.windows,
      slotIntervalMinutes: this.slotIntervalMinutes,
      minimumNoticeMinutes: this.minimumNoticeMinutes,
      bookingHorizonDays: this.bookingHorizonDays,
      approvalWindowHours: this.approvalWindowHours,
      durations: Duration.all().map((duration) => duration.minutes),
    };
  }
}
